export const ActionTypes = {

    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_ERROR: "SIGN_IN_ERROR",

    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",

    GET_SKILLS_SUCCESS: "GET_SKILLS_SUCCESS",

    GET_DATA_FROM_ASYNCSTORAGE: "GET_DATA_FROM_ASYNCSTORAGE",
    NAVIGATION_PROPS: "NAVIGATION_PROPS"
}